#
# Module manifest for module 'PSNessus'
#
# Generated by: David F. Severski
#
# Generated on: 2/26/2015
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PSNessus.psm1'

# Version number of this module.
ModuleVersion = '1.0'

# ID used to uniquely identify this module
GUID = 'fcbc8e15-c80d-4658-92f4-d57d35a6348b'

# Author of this module
Author = 'David F. Severski'

# Company or vendor of this module
CompanyName = "NA"

# Copyright statement for this module
Copyright = "(c) 2016 David F. Severski. All rights reserved."

# Description of the functionality provided by this module
Description = 'PowerShell interface for the Tenable Nessus scanner.'

# Minimum version of the Windows PowerShell engine required by this module
# PowerShellVersion = '2.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of the .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module
FunctionsToExport = 'Connect-Nessus', 'Disconnect-Nessus', 'Export-NessusHistory', 
                'Export-NessusStatus', 'Get-NessusExportFile', 'Get-NessusHistoryIds',
                'Get-NessusPolicies', 'Get-NessusScanHistory', 'Get-NessuScans',
                'Send-NessusRequest', 'Start-NessusScan'

# Cmdlets to export from this module
CmdletsToExport = ''

# Variables to export from this module
VariablesToExport = ''

# Aliases to export from this module
AliasesToExport = ''

# List of all modules packaged with this module.
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'tenable', 'nessus', 'security', 'network', 'api', 'vulnerabilty'

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/davidski/PSNessus/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/davidski/PSNessus'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

    } # End of PSData hashtable

} # End of PrivateData hashtable


# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

